name: Build

on:
  workflow_dispatch:
  push:
    tags: [REL-*]

env:
    MSTORSJO_REL: 20241001

jobs:
  Build:
    name: Build for ${{ matrix.target }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - i486
          - i586

    steps:
      - name: Checkout LLVM-MinGW
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: mstorsjo/llvm-mingw
          ref: ${{ env.MSTORSJO_REL }}
          path: llvm-mingw

      - name: Fetch LLVM-MinGW distribution
        uses:  dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: mstorsjo/llvm-mingw
          version: tags/${{ env.MSTORSJO_REL }}
          file: llvm-mingw-${{ env.MSTORSJO_REL }}-msvcrt-ubuntu-20.04-x86_64.tar.xz
          target: llvm-mingw-dst.tar.xz

      - name: Extract LLVM-MinGW distribution
        run: tar xf llvm-mingw-dst.tar.xz

      - name: Build MinGW-w64 libraries
        env:
          ARCHS: i686
          CRT_CONFIG_FLAGS: CFLAGS=-march=${{ matrix.target }}
        run: |
          export PATH=${{ github.workspace }}/llvm-mingw-${{ env.MSTORSJO_REL }}-msvcrt-ubuntu-20.04-x86_64/bin:$PATH
          cd llvm-mingw
          ./build-mingw-w64.sh \
            --with-default-win32-winnt=0x400 \
            --with-default-msvcrt=msvcrt \
            --enable-cfguard \
            out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bulwa-${{ matrix.target }}
          path: llvm-mingw/out

  Release:

    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Fetch build output
        uses: actions/download-artifact@v4
          
      - name: Prepare archives
        run: |
          cd bulwa-i486 && zip -r ../bulwa-${{ github.ref_name }}-i486.zip * && cd ..
          cd bulwa-i586 && zip -r ../bulwa-${{ github.ref_name }}-i586.zip * && cd ..

      - name: Prepare archives
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: |
            bulwa-${{ github.ref_name }}-i486.zip
            bulwa-${{ github.ref_name }}-i586.zip
